# -*- coding: utf-8 -*-
{
	'name'		:'Cargo Handling CM Airlines',
	'version'	:'17.0',
    'license': 'LGPL-3',
	'author'	:'Oniel, CMAirlines',
    'category': 'Accounting/Accounting',
	'description'	:"""Module for cargo handling through quotations and sales for airlines.""",
	'depends':['base','sale','cm_cai','account','cm_banks','account_fiscal_year_period','report_xlsx','mail','cm_sales', 'settlement'],
	'data':[
		'security/groups.xml',
		'security/ir.model.access.csv',
		'data/cron.xml',
		'data/sequences.xml',
		'data/paperformat.xml',
		'wizards/wizard_reception.xml',
		'wizards/wizard_modify_cargo_manifest.xml',
		'wizards/wizard_cancel.xml',
		'wizards/discard_guide.xml',
		'views/cargo_bill_view.xml',
		'views/cargo_type_view.xml',
		'views/airport_view.xml',
        'views/rel_airports_view.xml',
		'views/station_view.xml',
		'views/product_product.xml',
		'views/cargo_services_view.xml',
		'views/content_description_view.xml',
		'views/pricelist_handling_view.xml',
		'views/sale_order_handling.xml',
		'views/cargo_manifest.xml',
		'views/logs.xml',
		'views/cm_prepago_view.xml',
		'views/move_inh_view.xml',
		'views/discounts_view.xml',
		'views/res_company_inherit.xml',
        'views/menus.xml',
		'report/mother_guide.xml',
		'report/child_guides.xml',
		'report/invoice_order.xml',
		'report/main_template.xml',
		'report/report_cargo_manifest.xml',
		'report/invoice_guide.xml',
		'report/report_reports.xml'
	],
	'installable':True,
}
