# -*- coding: utf-8 -*-
{
	'name'		:'Cargo Handling CM Airlines',
	'version'	:'17.0',
    'license': 'LGPL-3',
	'author'	:'Oniel, CMAirlines',
    'category': 'Accounting/Accounting',
	'description'	:"""Module for cargo handling through quotations and sales for airlines.""",
	'depends':['base','sale','cm_cai','account','cm_banks','account_fiscal_year_period','report_xlsx','mail'],
	'data':[
		'security/groups.xml',
		'security/ir.model.access.csv',
		# 'wizard/additional_charge_wizard.xml',
		# 'wizard/wizard_account_status_inherit.xml',
		# 'data/res_partner_data.xml',
		'data/sequences.xml',
		# 'data/report_format_paper.xml',
		# 'views/res_partner_view.xml',
		# 'views/sale_order.xml',
		# 'views/cargo_bill_view.xml',
		'views/cargo_type_view.xml',
		'views/airport_view.xml',
        'views/rel_airports_view.xml',
		'views/station_view.xml',
		'views/product_product.xml',
		'views/cargo_services_view.xml',
		'views/content_description_view.xml',
		# 'views/account_invoice.xml',
		'views/res_company_inherit.xml',
		'views/pricelist_handling_view.xml',
		'views/sale_order_handling.xml',
		# 'views/cm_prepago_view.xml',
		# 'views/crm_lost_reason.xml',
		# #'views/view_configuration_inherit.xml',
		# 'reports/report_handling.xml',
		# 'reports/report_handling_guia.xml',
		# 'reports/report_cash_receipt.xml',
		# 'reports/report_accout_status_inherit.xml',
		# 'reports/report_reports.xml',

		# 'views/account.xml',
        # 'views/cb_history.xml',
		# 'data/planification.xml',
        'views/menus.xml'
	],
	'installable':True,
}
