from . import wizard_modify_cargo_manifest
from . import wizard_reception
from . import wizard_cancel
from . import discard_guide
from . import register_payment_inh
from . import handling_reports
from . import daily_sales_agent
from . import pending_settlement_inh
from . import custom_invoice_send
from . import ventas_cliente_wizard